[package]
name = "main"
path = "bin/structs_test_2.rs"
version = "0.1.0"
authors = ["Cyclip <40525455+Cyclip@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
